Repository dasch-swiss/beol, pull requests merged in 2020-09, with the labels that each got.

#170 Update names and links on the landing page
  src/app/landing-page/landing-page.component.html
Labels: refactor

#171 Search Mode: Adapt Route Segment
  src/app/correspondence/correspondence.component.ts
  src/app/landing-page/landing-page.component.ts
Labels: bug

#169 Oups error removed
  src/app/search-results/search-results.component.html
  src/app/search-results/search-results.component.ts
Labels: refactor

#172 Search Results
  src/app/search-results/search-results.component.html
  src/app/search-results/search-results.component.ts
  src/assets/style/_elements.scss
  src/styles.scss
Labels: bug

#174 Use strict build options
  src/app/introduction/introduction.component.html
  src/app/properties/read-text-value/read-text-value.component.html
  src/app/resource/beol-resource.ts
  src/app/resource/simpleResource/simpleResource.component.html
  src/app/search-results/search-results.component.html
  tsconfig.json
Labels: enhancement

#173 Use property's label to display a URI
  package-lock.json
  package.json
  src/app/resource/biblio-items/biblio-items.component.html
  src/app/resource/leibniz-letter/leibniz-letter.component.html
  src/app/resource/letter/letter.component.html
  src/app/resource/newton-letter/newton-letter.component.html
Labels: enhancement
